/*
 * generated by Xtext 2.17.1
 */
package fr.abes.sudoqual


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DlgpRuntimeModule extends AbstractDlgpRuntimeModule {
}
