/*
 * generated by Xtext 2.17.1
 */
package fr.abes.sudoqual


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DlgpStandaloneSetup extends DlgpStandaloneSetupGenerated {

	def static void doSetup() {
		new DlgpStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
